""" 
-> PESSOA DIGITA O PATRIMONIO, PROGRAMA TEM QUE LER NA PLANILHA O 
EQUIPAMENTO E ABRIR A FICHA PRA PREENCHER MEDICOES;
-> QUANDO O USUARIO SALVAR A PLANILHA, TEM Q VERIFICAR O MODELO, PATRIMONIO, 
ERRO% E DATA;
-> SALVA O ARQUIVO NA PASTA CERTA DE ACORDO COM EQUIPAMENTO;
-> ENTRAR NA PASTA CALIBRACAO H:\DOCUMENTOS\CALIBRAÇÃO;
-> VERIFICAR NA PLANILHA SE É INTERNO/EXTERNO;
-> INTERNO -> PEGA NOME EQUIPAMENTO E SEU PATRIMONIO;
-> ENTRA NA PASTA Q TEM O NOME DO EQUIPAMENTO E VERIFICA SE TEM O 
DOCUMENTO DE CALIBRAÇÃO COM O PATRIMONIO;
-> CRIA PLANILHA DE FICHA DE CONTROLE INSTRUMENTOS COM BASE NOS DB E 
SE TIVER TUDO CERTO COM A PLANILHA GERA PDF NA PASTA DO EQUIPAMENTO;
-> NO EXTERNO VERIFICAR SE TEM MAIS DE UMA PAGINA NO PDF;
"""